# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/development/cicd/templates/
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Python.gitlab-ci.yml

# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
default:
  image: python:latest
  # https://pip.pypa.io/en/stable/topics/caching/
  cache:
    paths:
      - .cache/pip
    key:
      file:
        - requirements.txt
  before_script:
    - python --version ; pip --version  # For debugging
    - python -mvenv .venv
    - source .venv/bin/activate

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

test:
  script:
    - pip install -r requirements.txt
    - python manage.py test
