# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/development/cicd/templates/
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Python.gitlab-ci.yml

stages:
  - test
  - build
  - release

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

unit tests:
  stage: test
  # Official language image. Look for the different tagged releases at:
  # https://hub.docker.com/r/library/python/tags/
  image: python:latest
  rules:
    # Run on push to master or on merge requests
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_PIPELINE_SOURCE == "merge_request_event"
  cache:
    # https://pip.pypa.io/en/stable/topics/caching/
    paths:
      - .cache/pip
    key:
      files:
        - requirements.txt
  script:
    - python --version ; pip --version  # For debugging
    - pip install -r requirements.txt
    - python manage.py test

docker build:
  stage: build
  image: docker:29-cli
  services:
    - docker:dind
  rules:
    # Only run for new version tags
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+(\.\d+)?$/
      exists:
        - contrib/docker/Dockerfile
      when: always
    - when: never
  variables:
    DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  script:
    - docker build --pull --tag $DOCKER_IMAGE_NAME -f contrib/docker/Dockerfile .
    - docker tag $DOCKER_IMAGE_NAME $CI_REGISTRY_IMAGE:${CI_COMMIT_TAG:1}
    - docker tag $DOCKER_IMAGE_NAME $CI_REGISTRY_IMAGE:latest
    - docker push --all-tags $CI_REGISTRY_IMAGE

create release:
  stage: release
  image: registry.gitlab.com/gitlab-org/cli:latest
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+(\.\d+)?$/
  script:
    - echo "Creating release $CI_COMMIT_TAG with description '$CI_COMMIT_TAG_MESSAGE'"
  release:
    tag_name: $CI_COMMIT_TAG
    description: |
      $CI_COMMIT_TAG_MESSAGE
