[project]
name = "workout-tracker"
version = "0.7.3"
requires-python = ">=3.12"
dependencies = [
    "asgiref==3.11.1",
    "django>=6.0.0,<6.1.0",
    "django-debug-toolbar==6.2.0",
    "psycopg==3.3.2",
    "sqlparse==0.5.5",
]

[dependency-groups]
dev = [
    "django-debug-toolbar>=6.1.0",
]

[tool.ruff.lint.per-file-ignores]
"worksheet/migrations/*" = ["RUF012"]
"worksheet/{admin,forms,models,managers}.py" = ["RUF012"]
