# Generated by Django 5.2.6 on 2025-11-06 16:42

import django.core.validators
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

def make_dates_unique(apps, schema_editor):
    target_tz = getattr(settings, "CURRENT_TIME_ZONE", settings.TIME_ZONE)
    Worksheet = apps.get_model("worksheet", "Worksheet")
    for w in Worksheet.objects.all():
        w.date = django.utils.timezone.localdate(w.started_at, target_tz)
        w.save()

class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0004_alter_result_reps'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='worksheet',
            name='unique_worsheet_per_day',
        ),
        migrations.RemoveField(
            model_name='worksheet',
            name='date',
        ),
        migrations.AlterField(
            model_name='result',
            name='reps',
            field=models.SmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0, message='Number of reps cannot be negative')]),
        ),
        migrations.AlterField(
            model_name='result',
            name='weight',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, message='Used weight cannot be negative')]),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='worksheet',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.RunPython(
            # Make sure dates are unique before adding the constraint
            make_dates_unique
        ),
        migrations.AddConstraint(
            model_name='worksheet',
            constraint=models.UniqueConstraint(fields=('date',), name='unique_worsheet_per_day'),
        ),
    ]
