# Generated by Django 5.2.6 on 2025-11-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0006_result_reps_and_weight_positive'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='worksheet',
            name='unique_worsheet_per_day',
        ),
        migrations.AddConstraint(
            model_name='worksheet',
            constraint=models.UniqueConstraint(fields=('date',), name='unique_worksheet_per_day'),
        ),
    ]
