# Generated by Django 5.2.6 on 2025-12-18 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0007_fix_typo_in_constraint_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='worksheet.workout'),
        ),
    ]
