# Generated by Django 5.2.6 on 2025-10-21 14:49

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('weight', models.BooleanField(default=False, verbose_name='Use weights?')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('repeat', models.BooleanField(default=False, verbose_name='Repeat workout exercises?')),
                ('exercises', models.ManyToManyField(through='workout.Program', to='workout.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.SmallIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.workout')),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.workout'),
        ),
        migrations.CreateModel(
            name='Worksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_progress', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.GeneratedField(db_persist=True, expression=django.db.models.functions.datetime.TruncDate(models.F('started_at')), output_field=models.DateField())),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workout.workout')),
            ],
        ),
        migrations.AlterOrderWithRespectTo(
            name='program',
            order_with_respect_to='workout',
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('weight', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workout.exercise')),
                ('worksheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.worksheet')),
            ],
            options={
                'order_with_respect_to': 'worksheet',
            },
        ),
    ]
