# Generated by Django 5.2.6 on 2025-10-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='worksheet',
            constraint=models.UniqueConstraint(fields=('date',), name='unique_worsheet_per_day'),
        ),
    ]
