# Generated by Django 5.2.6 on 2025-10-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_worksheet_unique_worsheet_per_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worksheet',
            name='in_progress',
        ),
        migrations.AddField(
            model_name='worksheet',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
