# Generated by Django 5.2.6 on 2025-12-18 16:02

from django.db import migrations

def copy_data(apps, schema_editor):
    Schedule = apps.get_model('worksheet', 'Schedule')
    NewSchedule = apps.get_model('schedule', 'Schedule')
    NewSchedule.objects.bulk_create(Schedule.objects.all())

    db_alias = schema_editor.connection.alias
    if db_alias == 'pg':
        with schema_editor.connection.cursor() as cursor:
            cursor.execute('''SELECT setval(pg_get_serial_sequence('"schedule_schedule"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "schedule_schedule";''')

def copy_data_reverse(apps, schema_editor):
    Schedule = apps.get_model('schedule', 'Schedule')
    OldSchedule = apps.get_model('worksheet', 'Schedule')
    OldSchedule.objects.bulk_create(Schedule.objects.all())

    db_alias = schema_editor.connection.alias
    if db_alias == 'pg':
        with schema_editor.connection.cursor() as cursor:
            cursor.execute('''SELECT setval(pg_get_serial_sequence('"worksheet_schedule"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "worksheet_schedule";''')

class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(copy_data, copy_data_reverse),
    ]
